
import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
  availableLanguages: Array<{code: string, name: string, flag: string}>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'Secure Login to Continue': 'Secure Login to Continue',
    'Please enter a valid 10-digit mobile number': 'Please enter a valid 10-digit mobile number',
    'OTP sent successfully! Use 123456 for demo': 'OTP sent successfully! Use 123456 for demo',
    'Invalid OTP. Please try again.': 'Invalid OTP. Please try again.',
    'Please fill in all fields': 'Please fill in all fields',
    'Invalid email or password': 'Invalid email or password',
    'Enter Mobile Number': 'Enter Mobile Number',
    'Verify OTP': 'Verify OTP',
    'Email Login': 'Email Login',
    'Continue with Google': 'Continue with Google',
    'or': 'or',
    'Enter 10-digit mobile number': 'Enter 10-digit mobile number',
    'Sending OTP...': 'Sending OTP...',
    'Send OTP': 'Send OTP',
    'Enter 6-digit OTP': 'Enter 6-digit OTP',
    'Verifying...': 'Verifying...',
    'Verify & Login': 'Verify & Login',
    'Change Mobile Number': 'Change Mobile Number',
    'Email Address': 'Email Address',
    'Password': 'Password',
    'Sign In...': 'Sign In...',
    'Sign In': 'Sign In',
    'Phone': 'Phone',
    "Don't have an account?": "Don't have an account?",
    'Sign Up': 'Sign Up',
    'తెలుగు': 'తెలుగు',
    'English': 'English',
    'Create Account': 'Create Account',
    'Join Mee Saaradhi Platform': 'Join Mee Saaradhi Platform',
    'Aadhaar number must be 12 digits': 'Aadhaar number must be 12 digits',
    'Invalid PAN format': 'Invalid PAN format',
    'Profile Photo (Passport Size)': 'Profile Photo (Passport Size)',
    'Back': 'Back',
    'Creating Account...': 'Creating Account...',
    'An error occurred during signup': 'An error occurred during signup',
    'Google signup failed': 'Google signup failed',
    'Email is required': 'Email is required',
    'Password is required': 'Password is required',
    'Passwords do not match': 'Passwords do not match',
    'Full name is required': 'Full name is required',
    'Profile photo is required': 'Profile photo is required',
    'Failed to upload photo': 'Failed to upload photo',
    'already registered': 'Email already registered',
    'Personal Information': 'Personal Information',
    'Full Name': 'Full Name',
    'Age': 'Age',
    'Phone Number': 'Phone Number',
    'Date of Birth': 'Date of Birth',
    'Aadhaar Number (12 digits)': 'Aadhaar Number (12 digits)',
    'PAN Number': 'PAN Number',
    'Enter your full name': 'Enter your full name',
    'Hello! How can I help you today?': 'Hello! How can I help you today?',
    'Chat Support': 'Chat Support',
    "We're here to help!": "We're here to help!",
    'Type your message...': 'Type your message...',
    'Thank you for your message. Our support team will assist you shortly.': 'Thank you for your message. Our support team will assist you shortly.',
    'Complaint History': 'Complaint History',
    'Monitor and track all your grievances': 'Monitor and track all your grievances',
    'Search by complaint ID, description, or category...': 'Search by complaint ID, description, or category...',
    'All Categories': 'All Categories',
    'All Complaints': 'All Complaints',
    'No complaints found matching the selected filters.': 'No complaints found matching the selected filters.',
    'Filter by Category': 'Filter by Category',
    'User': 'User',
    'Welcome to Mee Saaradhi': 'Welcome to Mee Saaradhi',
    'Your Digital Grievance Platform': 'Your Digital Grievance Platform',
    'Logout': 'Logout',
    'File New Complaint': 'File New Complaint',
    'Report your grievance in just a few steps': 'Report your grievance in just a few steps',
    'Start': 'Start',
    'Complaint Categories': 'Complaint Categories',
    'Quick Actions': 'Quick Actions',
    'Pensions': 'Pensions',
    'Roads & Infrastructure': 'Roads & Infrastructure',
    'Health Services': 'Health Services',
    'Water Supply': 'Water Supply',
    'Electricity': 'Electricity',
    'Ration & PDS': 'Ration & PDS',
    'Service Guide': 'Service Guide',
    'Emergency Support': 'Emergency Support',
    'Admin Panel': 'Admin Panel',
    'Quick Process': 'Quick Process',
    'Real-time Tracking': 'Real-time Tracking',
    'Fast Resolution': 'Fast Resolution',
    'Click to file complaint': 'Click to file complaint',
    'Access quickly from here': 'Access quickly from here'
  },
  te: {
    'Secure Login to Continue': 'కొనసాగించడానికి సురక్షితంగా ప్రవేశించండి',
    'Please enter a valid 10-digit mobile number': 'దయచేసి చెల్లుబాటు అయ్యే 10 అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి',
    'OTP sent successfully! Use 123456 for demo': 'OTP విజయవంతంగా పంపబడింది! డెమో కోసం 123456 ఉపయోగించండి',
    'Invalid OTP. Please try again.': 'చెల్లని OTP. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    'Please fill in all fields': 'దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి',
    'Invalid email or password': 'చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్',
    'Enter Mobile Number': 'మొబైల్ నంబర్ నమోదు చేయండి',
    'Verify OTP': 'OTPని ధృవీకరించండి',
    'Email Login': 'ఇమెయిల్ లాగిన్',
    'Continue with Google': 'Googleతో కొనసాగించండి',
    'or': 'లేదా',
    'Enter 10-digit mobile number': '10 అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి',
    'Sending OTP...': 'OTP పంపబడుతోంది...',
    'Send OTP': 'OTP పంపండి',
    'Enter 6-digit OTP': '6-అంకెల OTPని నమోదు చేయండి',
    'Verifying...': 'ధృవీకరిస్తోంది...',
    'Verify & Login': 'ధృవీకరించి లాగిన్ అవ్వండి',
    'Change Mobile Number': 'మొబైల్ నంబర్ మార్చండి',
    'Email Address': 'ఇమెయిల్ చిరునామా',
    'Password': 'పాస్‌వర్డ్',
    'Sign In...': 'సైన్ ఇన్ చేస్తోంది...',
    'Sign In': 'సైన్ ఇన్',
    'Phone': 'ఫోన్',
    "Don't have an account?": 'ఖాతా లేదా?',
    'Sign Up': 'సైన్ అప్',
    'తెలుగు': 'తెలుగు',
    'English': 'ఆంగ్లం',
    'Create Account': 'ఖాతా సృష్టించండి',
    'Join Mee Saaradhi Platform': 'Mee Saaradhi వేదికలో చేరండి',
    'Aadhaar number must be 12 digits': 'ఆధార్ నంబర్ 12 అంకెలు ఉండాలి',
    'Invalid PAN format': 'చెల్లని PAN ఫార్మాట్',
    'Profile Photo (Passport Size)': 'ప్రొఫైల్ ఫోటో (పాస్‌పోర్ట్ సైజు)',
    'Back': 'వెనుకకు',
    'Creating Account...': 'ఖాతా సృష్టిస్తోంది...',
    'An error occurred during signup': 'సైన్అప్ సమయంలో లోపం జరిగింది',
    'Google signup failed': 'Google సైన్అప్ విఫలమైంది',
    'Email is required': 'ఇమెయిల్ అవసరం',
    'Password is required': 'పాస్‌వర్డ్ అవసరం',
    'Passwords do not match': 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
    'Full name is required': 'పూర్తి పేరు అవసరం',
    'Profile photo is required': 'ప్రొఫైల్ ఫోటో అవసరం',
    'Failed to upload photo': 'ఫోటో అప్‌లోడ్ చేయడం విఫలమైంది',
    'already registered': 'ఇమెయిల్ ఇప్పటికే నమోదు చేయబడింది',
    'Personal Information': 'వ్యక్తిగత సమాచారం',
    'Full Name': 'పూర్తి పేరు',
    'Age': 'వయస్సు',
    'Phone Number': 'ఫోన్ నంబర్',
    'Date of Birth': 'పుట్టిన తేది',
    'Aadhaar Number (12 digits)': 'ఆధార్ నంబర్ (12 అంకెలు)',
    'PAN Number': 'పాన్ నంబర్',
    'Enter your full name': 'మీ పూర్తి పేరు నమోదు చేయండి',
    'Hello! How can I help you today?': 'హలో! ఈ రోజు నేను మీకు ఎలా సహాయం చేయగలను?',
    'Chat Support': 'చాట్ మద్దతు',
    "We're here to help!": 'మేము సహాయం చేయడానికి ఇక్కడ ఉన్నాము!',
    'Type your message...': 'మీ సందేశాన్ని టైప్ చేయండి...',
    'Thank you for your message. Our support team will assist you shortly.': 'మీ సందేశానికి ధన్యవాదాలు. మా మద్దతు బృందం త్వరలో మీకు సహాయం చేస్తుంది.',
    'Complaint History': 'ఫిర్యాదు చరిత్ర',
    'Monitor and track all your grievances': 'మీ అన్ని ఫిర్యాదులను పర్యవేక్షించండి మరియు ట్రాక్ చేయండి',
    'Search by complaint ID, description, or category...': 'ఫిర్యాదు ID, వివరణ లేదా వర్గం ద్వారా వెతకండి...',
    'All Categories': 'అన్ని వర్గాలు',
    'All Complaints': 'అన్ని ఫిర్యాదులు',
    'No complaints found matching the selected filters.': 'ఎంచుకున్న ఫిల్టర్‌లకు సరిపోలే ఫిర్యాదులు కనుగొనబడలేదు.',
    'Filter by Category': 'వర్గం ద్వారా ఫిల్టర్ చేయండి',
    'User': 'వినియోగదారు',
    'Welcome to Mee Saaradhi': '\"మీ సారధి\" కి స్వాగతం',
    'Your Digital Grievance Platform': 'మీ డిజిటల్ ఫిర్యాదు వేదిక',
    'Logout': 'లాగ్ అవుట్',
    'File New Complaint': 'కొత్త ఫిర్యాదు దాఖలు చేయండి',
    'Report your grievance in just a few steps': 'కేవలం కొన్ని దశల్లో మీ ఫిర్యాదును నివేదించండి',
    'Start': 'ప్రారంభించండి',
    'Complaint Categories': 'ఫిర్యాదు వర్గాలు',
    'Quick Actions': 'త్వరిత చర్యలు',
    'Pensions': 'పెన్షన్లు',
    'Roads & Infrastructure': 'రోడ్లు మరియు మౌలిక వసతులు',
    'Health Services': 'ఆరోగ్య సేవలు',
    'Water Supply': 'నీటి సరఫరా',
    'Electricity': 'విద్యుత్',
    'Ration & PDS': 'రేషన్ మరియు PDS',
    'Service Guide': 'సేవా మార్గదర్శి',
    'Emergency Support': 'అత్యవసర మద్దతు',
    'Admin Panel': 'నిర్వాహక ప్యానెల్',
    'Quick Process': 'త్వరిత ప్రక్రియ',
    'Real-time Tracking': 'నిజ-సమయ ట్రాకింగ్',
    'Fast Resolution': 'వేగంగా పరిష్కారం',
    'Click to file complaint': 'ఫిర్యాదు దాఖలు చేయడానికి క్లిక్ చేయండి',
    'Access quickly from here': 'ఇక్కడ నుండి త్వరగా ప్రవేశించండి'
  },
  hi: {
    'Secure Login to Continue': 'जारी रखने के लिए सुरक्षित लॉगिन',
    'Please enter a valid 10-digit mobile number': 'कृपया एक मान्य 10-अंकीय मोबाइल नंबर दर्ज करें',
    'OTP sent successfully! Use 123456 for demo': 'OTP सफलतापूर्वक भेजा गया! डेमो के लिए 123456 का उपयोग करें',
    'Invalid OTP. Please try again.': 'अमान्य OTP। कृपया पुनः प्रयास करें।',
    'Please fill in all fields': 'कृपया सभी फ़ील्ड भरें',
    'Invalid email or password': 'अमान्य ईमेल या पासवर्ड',
    'Enter Mobile Number': 'मोबाइल नंबर दर्ज करें',
    'Verify OTP': 'OTP सत्यापित करें',
    'Email Login': 'ईमेल लॉगिन',
    'Continue with Google': 'Google के साथ जारी रखें',
    'or': 'या',
    'Enter 10-digit mobile number': '10-अंकीय मोबाइल नंबर दर्ज करें',
    'Sending OTP...': 'OTP भेजा जा रहा है...',
    'Send OTP': 'OTP भेजें',
    'Enter 6-digit OTP': '6-अंकीय OTP दर्ज करें',
    'Verifying...': 'सत्यापित कर रहे हैं...',
    'Verify & Login': 'सत्यापित करें और लॉगिन करें',
    'Change Mobile Number': 'मोबाइल नंबर बदलें',
    'Email Address': 'ईमेल पता',
    'Password': 'पासवर्ड',
    'Sign In...': 'साइन इन...',
    'Sign In': 'साइन इन',
    'Phone': 'फोन',
    "Don't have an account?": 'खाता नहीं है?',
    'Sign Up': 'साइन अप',
    'తెలుగు': 'तेलुगु',
    'English': 'अंग्रेजी',
    'Create Account': 'खाता बनाएं',
    'Join Mee Saaradhi Platform': 'मी सारथी प्लेटफॉर्म से जुड़ें',
    'Welcome to Mee Saaradhi': 'मी सारथी में आपका स्वागत है',
    'Your Digital Grievance Platform': 'आपका डिजिटल शिकायत मंच',
    'Logout': 'लॉग आउट',
    'File New Complaint': 'नई शिकायत दर्ज करें',
    'Report your grievance in just a few steps': 'केवल कुछ चरणों में अपनी शिकायत दर्ज करें',
    'Start': 'शुरू करें',
    'Complaint Categories': 'शिकायत श्रेणियां',
    'Quick Actions': 'त्वरित कार्य',
    'Pensions': 'पेंशन',
    'Roads & Infrastructure': 'सड़कें और बुनियादी ढांचा',
    'Health Services': 'स्वास्थ्य सेवाएं',
    'Water Supply': 'जल आपूर्ति',
    'Electricity': 'बिजली',
    'Ration & PDS': 'राशन और PDS',
    'Service Guide': 'सेवा गाइड',
    'Emergency Support': 'आपातकालीन सहायता',
    'Admin Panel': 'एडमिन पैनल',
    'Complaint History': 'शिकायत इतिहास',
    'Quick Process': 'त्वरित प्रक्रिया',
    'Real-time Tracking': 'वास्तविक समय ट्रैकिंग',
    'Fast Resolution': 'तेज़ समाधान',
    'Click to file complaint': 'शिकायत दर्ज करने के लिए क्लिक करें',
    'Access quickly from here': 'यहां से तुरंत पहुंचें'
  },
  ta: {
    'Welcome to Mee Saaradhi': 'மீ சாரதிக்கு வரவேற்கிறோம்',
    'Your Digital Grievance Platform': 'உங்கள் டிஜிட்டல் புகார் தளம்',
    'Logout': 'வெளியேறு',
    'File New Complaint': 'புதிய புகார் பதிவு செய்யுங்கள்',
    'Report your grievance in just a few steps': 'சில படிகளில் உங்கள் புகாரை தெரிவிக்கவும்',
    'Start': 'தொடங்கு',
    'Complaint Categories': 'புகார் வகைகள்',
    'Quick Actions': 'விரைவு செயல்கள்',
    'Pensions': 'ஓய்வூதியங்கள்',
    'Roads & Infrastructure': 'சாலைகள் மற்றும் உள்கட்டமைப்பு',
    'Health Services': 'சுகாதார சேவைகள்',
    'Water Supply': 'நீர் வழங்கல்',
    'Electricity': 'மின்சாரம்',
    'Ration & PDS': 'ரேஷன் மற்றும் PDS',
    'Service Guide': 'சேவை வழிகாட்டி',
    'Emergency Support': 'அவசர ஆதரவு',
    'Admin Panel': 'நிர்வாக பேனல்',
    'Complaint History': 'புகார் வரலாறு',
    'Quick Process': 'விரைவு செயல்முறை',
    'Real-time Tracking': 'நேரடி கண்காணிப்பு',
    'Fast Resolution': 'விரைவு தீர்வு',
    'Click to file complaint': 'புகார் பதிவு செய்ய கிளிக் செய்யுங்கள்',
    'Access quickly from here': 'இங்கிருந்து விரைவாக அணுகவும்'
  },
  kn: {
    'Welcome to Mee Saaradhi': 'ಮೀ ಸಾರಥಿಗೆ ಸ್ವಾಗತ',
    'Your Digital Grievance Platform': 'ನಿಮ್ಮ ಡಿಜಿಟಲ್ ದೂರಿನ ವೇದಿಕೆ',
    'Logout': 'ಲಾಗ್ ಔಟ್',
    'File New Complaint': 'ಹೊಸ ದೂರಿನನ್ನು ಸಲ್ಲಿಸಿ',
    'Report your grievance in just a few steps': 'ಕೆಲವೇ ಹಂತಗಳಲ್ಲಿ ನಿಮ್ಮ ದೂರಿನನ್ನು ವರದಿ ಮಾಡಿ',
    'Start': 'ಪ್ರಾರಂಭಿಸಿ',
    'Complaint Categories': 'ದೂರಿನ ವರ್ಗಗಳು',
    'Quick Actions': 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    'Pensions': 'ಪಿಂಚಣಿಗಳು',
    'Roads & Infrastructure': 'ರಸ್ತೆಗಳು ಮತ್ತು ಮೂಲಸೌಕರ್ಯ',
    'Health Services': 'ಆರೋಗ್ಯ ಸೇವೆಗಳು',
    'Water Supply': 'ನೀರು ಪೂರೈಕೆ',
    'Electricity': 'ವಿದ್ಯುತ್',
    'Ration & PDS': 'ರೇಷನ್ ಮತ್ತು PDS',
    'Service Guide': 'ಸೇವಾ ಮಾರ್ಗದರ್ಶಿ',
    'Emergency Support': 'ತುರ್ತು ಬೆಂಬಲ',
    'Admin Panel': 'ನಿರ್ವಾಹಕ ಫಲಕ',
    'Complaint History': 'ದೂರಿನ ಇತಿಹಾಸ',
    'Quick Process': 'ತ್ವರಿತ ಪ್ರಕ್ರಿಯೆ',
    'Real-time Tracking': 'ನೈಜ-ಸಮಯದ ಟ್ರ್ಯಾಕಿಂಗ್',
    'Fast Resolution': 'ವೇಗವಾದ ಪರಿಹಾರ',
    'Click to file complaint': 'ದೂರಿನನ್ನು ಸಲ್ಲಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    'Access quickly from here': 'ಇಲ್ಲಿಂದ ತ್ವರಿತವಾಗಿ ಪ್ರವೇಶಿಸಿ'
  }
};

const availableLanguages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' }
];

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'en' ? 'te' : 'en'));
  };

  const t = (key: string): string => {
    const translation = translations[language as keyof typeof translations]?.[key];
    if (typeof translation === 'string') {
      return translation;
    }
    // Fallback to English if current language translation is not found
    const fallback = translations['en'][key];
    if (typeof fallback === 'string') {
      return fallback;
    }
    // Return key if no translation found
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
