// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meweqoiqpncjfskngica.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ld2Vxb2lxcG5jamZza25naWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODEwMDYsImV4cCI6MjA2NjA1NzAwNn0.BahZ_XKW22D0tL8CTCx_LOhAjGzeNg1__uk55qsRbsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);